# MongoDB

### Setting things up

Remember to restart the kernel after running this code cell if you didn't already have pymongo installed (you only need to do this once)

In [27]:
pip install pymongo

Requirement already satisfied: pymongo in /Users/isaactabor/anaconda3/lib/python3.11/site-packages (4.7.2)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /Users/isaactabor/anaconda3/lib/python3.11/site-packages (from pymongo) (2.6.1)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pymongo
from pymongo import MongoClient
import pandas as pd

In [4]:
client = MongoClient('localhost', 27017)

In [5]:
client

MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True)

In [6]:
db = client.lms # "example" is the database name

In [7]:
collection = db.students ## collection within database

### Inserting/deleting data

MongoDB is made up of, in a simplified way, massive JSON objects

### Querying data

## courses

Let's explore some example data that might be similar to the type you are creating in your projects

In [8]:
courses = pd.read_csv('https://raw.githubusercontent.com/methinky/forge_project2/main/test_forge%20-%20Courses.csv')
courses

,Course_Name,Code,Description,Instructor
0,COMM_2020,12736,Introduction to Management Accounting,Roger Martin
1,STAT_1601,12564,Introduction to Data Science with R,Prince Afriyie
2,STAT_1601,12645,Introduction to Data Science with R,Richard Ross
3,STAT_1601,21031,Introduction to Data Science with R,Prince Afriyie
4,COMM_2020,14295,Introduction to Management Accounting,Roger Martin
5,COMM_3410,14730,Commercial Law I,Sherri Moore
6,COMM_3410,14731,Commercial Law I,Sherri Moore
7,SLAV_2360,11386,Dracula,Stanley Stephanic
8,APMA_3110,15413,Applied Statistics and Probability,Gary Koenig
9,MATH_3350,15762,Applied Linear Algebra,Jeffrey Holt
10,MATH_3350,15763,Applied Linear Algebra,Jeffrey Holt
11,MATH_3350,15764,Applied Linear Algebra,Jeffrey Holt

We can easily convert flat data to dictionary format with `to_dict()`

We can then insert it into our MongoDB

## Students

In [9]:
students = pd.read_csv("https://raw.githubusercontent.com/methinky/forge_project2/main/test_forge%20-%20Students.csv")
students

   Student_ID First_Name    Last_Name                Email
0      rqb6bc    Melissa        Zheng  rqb6bc@virginia.edu
1      pfg9yq       Anya    Hariharan  pfg9yq@virginia.edu
2      zds3st      Isaac        Tabor  zds3st@virginia.edu
3      jrp86y      Peter         Park  jrp86y@virginia.edu
4      mcf5yc      Aryan  Prabhudesai  mcf5yc@virginia.edu
5      ppz2ry       Alex        Jones  ppz2ry@virginia.edu
6      rin7tx     Cheryl    Abernathy  rin7tx@virginia.edu
7      vip4my    Colleen    Lindstrom  vip4my@virginia.edu
8      eru9fh      Robin         Park  eru9fh@virginia.edu
9      fmp6yj      Laura       Peters  fmp6yj@virginia.edu
10     fpn8kb   Nicholas    Spielberg  fpn8kb@virginia.edu
11     imc4bv    Douglas     Polansky  imc4bv@virginia.edu
12     svw7gw     Edward          Lee  svw7gw@virginia.edu
13     tmz7bd   Brittney         Reed  tmz7bd@virginia.edu
14     wdk0je     Tyrone        Twain  wdk0je@virginia.edu
15     clw3dh     Felipe       Mendez  clw3dh@virginia.edu

## StudentClasses

In [10]:
StudentClasses2 = pd.read_csv("https://raw.githubusercontent.com/methinky/forge_project2/main/test_forge%20-%20StudentClasses%20(2).csv")
StudentClasses2

     Code Student_ID
0   12736     rqb6bc
1   12736     svw7gw
2   12736     zds3st
3   12736     fmp6yj
4   12736     clw3dh
5   12564     ppz2ry
6   12564     pfg9yq
7   12564     zds3st
8   12564     jrp86y
9   12564     mcf5yc
10  12645     rin7tx
11  12645     vip4my
12  12645     eru9fh
13  12645     fmp6yj
14  12645     fpn8kb
15  21031     imc4bv
16  21031     svw7gw
17  21031     tmz7bd
18  21031     wdk0je
19  21031     clw3dh
20  14295     jrp86y
21  14295     mcf5yc
22  14295     eru9fh
23  14295     vip4my
24  14295     rin7tx
25  14730     rqb6bc
26  14730     pfg9yq
27  14730     zds3st
28  14730     jrp86y
29  14730     rin7tx
30  14731     vip4my
31  14731     eru9fh
32  14731     fmp6yj
33  14731     fpn8kb
34  14731     imc4bv
35  11386     rqb6bc
36  11386     pfg9yq
37  11386     zds3st
38  11386     jrp86y
39  11386     ppz2ry
40  15762     rqb6bc
41  15762     pfg9yq
42  15762     mcf5yc
43  15762     ppz2ry
44  15762     jrp86y
45  15763     rin7tx
46  15763     vip4my
47  15763     eru9fh
48  15763     fmp6yj
49  15763     fpn8kb
50  15764     imc4bv
51  15764     svw7gw
52  15764     tmz7bd
53  15764     wdk0je
54  15764     clw3dh
55  15413     vip4my
56  15413     svw7gw
57  15413     tmz7bd
58  15413     wdk0je
59  15413     clw3dh

In [11]:
Assignments = pd.read_csv("https://raw.githubusercontent.com/methinky/forge_project2/main/test_forge%20-%20Assignments%20(1).csv")
Assignments

   Assignment_Id   Code Assignment_Title  Weight  Date_Due
0        12736E1  12736           Exam 1     0.1  02/29/24
1        12736E2  12736           Exam 2     0.1  03/21/24
2         12736M  12736          Midterm     0.2  04/14/24
3         12736F  12736            Final     0.6  05/04/24
4        12564E1  12564           Exam 1     0.1  02/20/24
5        12564E2  12564           Exam 2     0.1  03/28/24
6         12564M  12564          Midterm     0.2  04/11/24
7         12564F  12564            Final     0.6  05/07/24
8        12645E1  12645           Exam 1     0.1  05/08/24
9        12645E2  12645           Exam 2     0.1  03/15/24
10        12645M  12645          Midterm     0.2  04/22/24
11        12645F  12645            Final     0.6  05/09/24
12       21031E1  21031           Exam 1     0.1  03/06/24
13       21031E2  21031           Exam 2     0.1  02/07/24
14        21031M  21031          Midterm     0.2  06/08/24
15        21031F  21031            Final     0.6  05/09/24
16       14295E1  14295           Exam 1     0.1  05/10/24
17       14295E2  14295           Exam 2     0.1  05/11/24
18        14295M  14295          Midterm     0.2  05/12/24
19        14295F  14295            Final     0.6  05/13/24
20       14730E1  14730           Exam 1     0.1  05/14/24
21       14730E2  14730           Exam 2     0.1  05/15/24
22        14730M  14730          Midterm     0.2  05/16/24
23        14730F  14730            Final     0.6  05/17/24
24       14731E1  14731           Exam 1     0.1  05/18/24
25       14731E2  14731           Exam 2     0.1  05/19/24
26        14731M  14731          Midterm     0.2  05/20/24
27        14731F  14731            Final     0.6  05/21/24
28       11386E1  11386           Exam 1     0.1  05/22/24
29       11386E2  11386           Exam 2     0.1  05/23/24
30        11386M  11386          Midterm     0.2  05/24/24
31        11386F  11386            Final     0.6  05/25/24
32       15413E1  15413           Exam 1     0.1  05/26/24
33       15413E2  15413           Exam 2     0.1  05/27/24
34        15413M  15413          Midterm     0.2  05/28/24
35        15413F  15413            Final     0.6  05/29/24
36       16742E1  16742           Exam 1     0.1  05/30/24
37       16742E2  16742           Exam 2     0.1  05/31/24
38        16742M  16742          Midterm     0.2  06/01/24
39        16742F  16742            Final     0.6  06/02/24
40       15762E1  15762           Exam 1     0.1  05/30/24
41       15762E2  15762           Exam 2     0.1  05/31/24
42        15762M  15762          Midterm     0.2  06/01/24
43        15762F  15762            Final     0.6  06/02/24
44       15763E1  15763           Exam 1     0.1  05/30/24
45       15763E2  15763           Exam 2     0.1  05/31/24
46        15763F  15763          Midterm     0.2  06/01/24
47        15763M  15763            Final     0.6  06/02/24
48       15764E1  15764           Exam 1     0.1  05/30/24
49       15764E2  15764           Exam 2     0.1  05/31/24
50        15764M  15764          Midterm     0.2  06/01/24
51        15764F  15764            Final     0.6  06/02/24

In [12]:
Grades = pd.read_csv("https://raw.githubusercontent.com/methinky/forge_project2/main/test_forge%20-%20Grades%20(1).csv")
Grades

    Student_ID Assignment_Id  Score Date_Submitted
0       rqb6bc       12736E1     78       02/29/24
1       rqb6bc       12736E2     92       03/21/24
2       rqb6bc        12736M     85       04/14/24
3       rqb6bc        12736F     64       05/04/24
4       svw7gw       12736E1     47       02/29/24
..         ...           ...    ...            ...
235     wdk0je        15764F    100       02/03/24
236     clw3dh       15764E1     93       03/24/24
237     clw3dh       15764E2    100       05/24/24
238     clw3dh        15764M     88       04/22/24
239     clw3dh        15764F     87       05/09/24

[240 rows x 4 columns]

Just like how we create data with dictionaries, we query data the same way

In [13]:
# Merge student_courses with students to get student names
student_courses_merged = pd.merge(StudentClasses2, students, on='Student_ID')

# Merge the result with courses to get course names
full_merge = pd.merge(student_courses_merged, courses, left_on='Code', right_on='Code')

# Merge assignments with courses to get course names
assignments_merged = pd.merge(Assignments, courses, on='Code')

# Merge grades with assignments to get assignment names
grades_merged = pd.merge(Grades, assignments_merged, on='Assignment_Id')

# Merge grades with students to get student names
grades_merged = pd.merge(grades_merged, students, on='Student_ID')

In [14]:
assignments_merged.head()

,Assignment_Id,Code,Assignment_Title,Weight,Date_Due,Course_Name,Description,Instructor
0,12736E1,12736,Exam 1,0.1,02/29/24,COMM_2020,Introduction to Management Accounting,Roger Martin
1,12736E2,12736,Exam 2,0.1,03/21/24,COMM_2020,Introduction to Management Accounting,Roger Martin
2,12736M,12736,Midterm,0.2,04/14/24,COMM_2020,Introduction to Management Accounting,Roger Martin
3,12736F,12736,Final,0.6,05/04/24,COMM_2020,Introduction to Management Accounting,Roger Martin
4,12564E1,12564,Exam 1,0.1,02/20/24,STAT_1601,Introduction to Data Science with R,Prince Afriyie

In [15]:
nested_data = []

for course_code, group in full_merge.groupby('Code'):
    course_name = group['Course_Name'].values[0]
    students = group[['Student_ID', 'First_Name','Last_Name','Email']].drop_duplicates().to_dict('records')
    
    # Get assignments for the course
    course_assignments = assignments_merged[assignments_merged['Code'] == course_code]
    assignments_list = []
    
    for _, assignment in course_assignments.iterrows():
        assignment_id = assignment['Assignment_Id']
        assignment_name = assignment['Assignment_Title']
        assignment_weight = assignment['Weight']
        
        # Get grades for the assignment
        assignment_grades = grades_merged[grades_merged['Assignment_Id'] == assignment_id]
        grades_list = assignment_grades[['Student_ID', 'Score']].to_dict('records')
        
        assignments_list.append({
            'Assignment_Id': assignment_id,
            'Assignment_Title': assignment_name,
            'Weight': assignment_weight,
            'Grades': grades_list
        })
    
    nested_data.append({
        'Code': course_code,
        'Course_Name': course_name,
        'Students': students,
        'Assignments': assignments_list
    })

In [16]:
nested_data

[{'Code': 11386,
  'Course_Name': 'SLAV_2360',
  'Students': [{'Student_ID': 'rqb6bc',
    'First_Name': 'Melissa',
    'Last_Name': 'Zheng',
    'Email': 'rqb6bc@virginia.edu'},
   {'Student_ID': 'zds3st',
    'First_Name': 'Isaac',
    'Last_Name': 'Tabor',
    'Email': 'zds3st@virginia.edu'},
   {'Student_ID': 'ppz2ry',
    'First_Name': 'Alex',
    'Last_Name': 'Jones',
    'Email': 'ppz2ry@virginia.edu'},
   {'Student_ID': 'pfg9yq',
    'First_Name': 'Anya',
    'Last_Name': 'Hariharan',
    'Email': 'pfg9yq@virginia.edu'},
   {'Student_ID': 'jrp86y',
    'First_Name': 'Peter',
    'Last_Name': 'Park',
    'Email': 'jrp86y@virginia.edu'}],
  'Assignments': [{'Assignment_Id': '11386E1',
    'Assignment_Title': 'Exam 1',
    'Weight': 0.1,
    'Grades': [{'Student_ID': 'rqb6bc', 'Score': 80},
     {'Student_ID': 'zds3st', 'Score': 77},
     {'Student_ID': 'pfg9yq', 'Score': 68},
     {'Student_ID': 'jrp86y', 'Score': 51}]},
   {'Assignment_Id': '11386E2',
    'Assignment_Title': 'Exam 2',
    'Weight': 0.1,
    'Grades': [{'Student_ID': 'rqb6bc', 'Score': 92},
     {'Student_ID': 'zds3st', 'Score': 70},
     {'Student_ID': 'pfg9yq', 'Score': 62},
     {'Student_ID': 'jrp86y', 'Score': 81}]},
   {'Assignment_Id': '11386M',
    'Assignment_Title': 'Midterm',
    'Weight': 0.2,
    'Grades': [{'Student_ID': 'rqb6bc', 'Score': 93},
     {'Student_ID': 'zds3st', 'Score': 85},
     {'Student_ID': 'pfg9yq', 'Score': 59},
     {'Student_ID': 'jrp86y', 'Score': 68}]},
   {'Assignment_Id': '11386F',
    'Assignment_Title': 'Final',
    'Weight': 0.6,
    'Grades': [{'Student_ID': 'rqb6bc', 'Score': 91},
     {'Student_ID': 'zds3st', 'Score': 64},
     {'Student_ID': 'pfg9yq', 'Score': 89},
     {'Student_ID': 'jrp86y', 'Score': 93}]}]},
 {'Code': 12564,
  'Course_Name': 'STAT_1601',
  'Students': [{'Student_ID': 'zds3st',
    'First_Name': 'Isaac',
    'Last_Name': 'Tabor',
    'Email': 'zds3st@virginia.edu'},
   {'Student_ID': 'ppz2ry',
    'First_Name': 'Alex',
    'Last_Name': 'Jones',
    'Email': 'ppz2ry@virginia.edu'},
   {'Student_ID': 'pfg9yq',
    'First_Name': 'Anya',
    'Last_Name': 'Hariharan',
    'Email': 'pfg9yq@virginia.edu'},
   {'Student_ID': 'jrp86y',
    'First_Name': 'Peter',
    'Last_Name': 'Park',
    'Email': 'jrp86y@virginia.edu'},
   {'Student_ID': 'mcf5yc',
    'First_Name': 'Aryan',
    'Last_Name': 'Prabhudesai',
    'Email': 'mcf5yc@virginia.edu'}],
  'Assignments': [{'Assignment_Id': '12564E1',
    'Assignment_Title': 'Exam 1',
    'Weight': 0.1,
    'Grades': [{'Student_ID': 'zds3st', 'Score': 52},
     {'Student_ID': 'pfg9yq', 'Score': 28},
     {'Student_ID': 'jrp86y', 'Score': 65},
     {'Student_ID': 'mcf5yc', 'Score': 38}]},
   {'Assignment_Id': '12564E2',
    'Assignment_Title': 'Exam 2',
    'Weight': 0.1,
    'Grades': [{'Student_ID': 'zds3st', 'Score': 89},
     {'Student_ID': 'pfg9yq', 'Score': 77},
     {'Student_ID': 'jrp86y', 'Score': 74},
     {'Student_ID': 'mcf5yc', 'Score': 54}]},
   {'Assignment_Id': '12564M',
    'Assignment_Title': 'Midterm',
    'Weight': 0.2,
    'Grades': [{'Student_ID': 'zds3st', 'Score': 31},
     {'Student_ID': 'pfg9yq', 'Score': 43},
     {'Student_ID': 'jrp86y', 'Score': 27},
     {'Student_ID': 'mcf5yc', 'Score': 81}]},
   {'Assignment_Id': '12564F',
    'Assignment_Title': 'Final',
    'Weight': 0.6,
    'Grades': [{'Student_ID': 'zds3st', 'Score': 100},
     {'Student_ID': 'pfg9yq', 'Score': 96},
     {'Student_ID': 'jrp86y', 'Score': 86},
     {'Student_ID': 'mcf5yc', 'Score': 49}]}]},
 {'Code': 12645,
  'Course_Name': 'STAT_1601',
  'Students': [{'Student_ID': 'fmp6yj',
    'First_Name': 'Laura',
    'Last_Name': 'Peters',
    'Email': 'fmp6yj@virginia.edu'},
   {'Student_ID': 'rin7tx',
    'First_Name': 'Cheryl',
    'Last_Name': 'Abernathy',
    'Email': 'rin7tx@virginia.edu'},
   {'Student_ID': 'vip4my',
    'First_Name': 'Colleen',
    'Last_Name': 'Lindstrom',
    'Email': 'vip4my@virginia.edu'},
   {'Student_ID': 'eru9fh',
    'First_Name': 'Robin',
    'Last_Name': 'Park',
    'Email': 'eru9fh@virginia.edu'},
   {'Student_ID': 'fpn8kb',
    'First_Name': 'Nicholas',
    'Last_Name': 'Spielberg',
    'Email': 'fpn8kb@virginia.edu'}],
  'Assignments': [{'Assignment_Id': '12645E1',
    'Assignment_Title': 'Exam 1',
    'Weight': 0.1,
    'Grades': [{'Student_ID': 'fmp6yj', 'Score': 76},
     {'Student_ID': 'rin7tx', 'Score': 93},
     {'Student_ID': 'vip4my', 'Score': 95},
     {'Student_ID': 'eru9fh', 'Score': 20},
     {'Student_ID': 'fpn8kb', 'Score': 39}]},
   {'Assignment_Id': '12645E2',
    'Assignment_Title': 'Exam 2',
    'Weight': 0.1,
    'Grades': [{'Student_ID': 'fmp6yj', 'Score': 68},
     {'Student_ID': 'rin7tx', 'Score': 33},
     {'Student_ID': 'vip4my', 'Score': 50},
     {'Student_ID': 'eru9fh', 'Score': 87},
     {'Student_ID': 'fpn8kb', 'Score': 70}]},
   {'Assignment_Id': '12645M',
    'Assignment_Title': 'Midterm',
    'Weight': 0.2,
    'Grades': [{'Student_ID': 'fmp6yj', 'Score': 29},
     {'Student_ID': 'rin7tx', 'Score': 72},
     {'Student_ID': 'vip4my', 'Score': 61},
     {'Student_ID': 'eru9fh', 'Score': 56},
     {'Student_ID': 'fpn8kb', 'Score': 45}]},
   {'Assignment_Id': '12645F',
    'Assignment_Title': 'Final',
    'Weight': 0.6,
    'Grades': [{'Student_ID': 'fmp6yj', 'Score': 97},
     {'Student_ID': 'rin7tx', 'Score': 44},
     {'Student_ID': 'vip4my', 'Score': 79},
     {'Student_ID': 'eru9fh', 'Score': 41},
     {'Student_ID': 'fpn8kb', 'Score': 63}]}]},
 {'Code': 12736,
  'Course_Name': 'COMM_2020',
  'Students': [{'Student_ID': 'rqb6bc',
    'First_Name': 'Melissa',
    'Last_Name': 'Zheng',
    'Email': 'rqb6bc@virginia.edu'},
   {'Student_ID': 'svw7gw',
    'First_Name': 'Edward',
    'Last_Name': 'Lee',
    'Email': 'svw7gw@virginia.edu'},
   {'Student_ID': 'zds3st',
    'First_Name': 'Isaac',
    'Last_Name': 'Tabor',
    'Email': 'zds3st@virginia.edu'},
   {'Student_ID': 'fmp6yj',
    'First_Name': 'Laura',
    'Last_Name': 'Peters',
    'Email': 'fmp6yj@virginia.edu'},
   {'Student_ID': 'clw3dh',
    'First_Name': 'Felipe',
    'Last_Name': 'Mendez',
    'Email': 'clw3dh@virginia.edu'}],
  'Assignments': [{'Assignment_Id': '12736E1',
    'Assignment_Title': 'Exam 1',
    'Weight': 0.1,
    'Grades': [{'Student_ID': 'rqb6bc', 'Score': 78},
     {'Student_ID': 'svw7gw', 'Score': 47},
     {'Student_ID': 'zds3st', 'Score': 36},
     {'Student_ID': 'fmp6yj', 'Score': 80},
     {'Student_ID': 'clw3dh', 'Score': 75}]},
   {'Assignment_Id': '12736E2',
    'Assignment_Title': 'Exam 2',
    'Weight': 0.1,
    'Grades': [{'Student_ID': 'rqb6bc', 'Score': 92},
     {'Student_ID': 'svw7gw', 'Score': 90},
     {'Student_ID': 'zds3st', 'Score': 88},
     {'Student_ID': 'fmp6yj', 'Score': 40},
     {'Student_ID': 'clw3dh', 'Score': 53}]},
   {'Assignment_Id': '12736M',
    'Assignment_Title': 'Midterm',
    'Weight': 0.2,
    'Grades': [{'Student_ID': 'rqb6bc', 'Score': 85},
     {'Student_ID': 'svw7gw', 'Score': 55},
     {'Student_ID': 'zds3st', 'Score': 23},
     {'Student_ID': 'fmp6yj', 'Score': 99},
     {'Student_ID': 'clw3dh', 'Score': 48}]},
   {'Assignment_Id': '12736F',
    'Assignment_Title': 'Final',
    'Weight': 0.6,
    'Grades': [{'Student_ID': 'rqb6bc', 'Score': 64},
     {'Student_ID': 'svw7gw', 'Score': 71},
     {'Student_ID': 'zds3st', 'Score': 59},
     {'Student_ID': 'fmp6yj', 'Score': 67},
     {'Student_ID': 'clw3dh', 'Score': 82}]}]},
 {'Code': 14295,
  'Course_Name': 'COMM_2020',
  'Students': [{'Student_ID': 'jrp86y',
    'First_Name': 'Peter',
    'Last_Name': 'Park',
    'Email': 'jrp86y@virginia.edu'},
   {'Student_ID': 'mcf5yc',
    'First_Name': 'Aryan',
    'Last_Name': 'Prabhudesai',
    'Email': 'mcf5yc@virginia.edu'},
   {'Student_ID': 'rin7tx',
    'First_Name': 'Cheryl',
    'Last_Name': 'Abernathy',
    'Email': 'rin7tx@virginia.edu'},
   {'Student_ID': 'vip4my',
    'First_Name': 'Colleen',
    'Last_Name': 'Lindstrom',
    'Email': 'vip4my@virginia.edu'},
   {'Student_ID': 'eru9fh',
    'First_Name': 'Robin',
    'Last_Name': 'Park',
    'Email': 'eru9fh@virginia.edu'}],
  'Assignments': [{'Assignment_Id': '14295E1',
    'Assignment_Title': 'Exam 1',
    'Weight': 0.1,
    'Grades': [{'Student_ID': 'jrp86y', 'Score': 93},
     {'Student_ID': 'mcf5yc', 'Score': 83},
     {'Student_ID': 'rin7tx', 'Score': 68},
     {'Student_ID': 'vip4my', 'Score': 60},
     {'Student_ID': 'eru9fh', 'Score': 81}]},
   {'Assignment_Id': '14295E2',
    'Assignment_Title': 'Exam 2',
    'Weight': 0.1,
    'Grades': [{'Student_ID': 'jrp86y', 'Score': 73},
     {'Student_ID': 'mcf5yc', 'Score': 78},
     {'Student_ID': 'rin7tx', 'Score': 85},
     {'Student_ID': 'vip4my', 'Score': 75},
     {'Student_ID': 'eru9fh', 'Score': 88}]},
   {'Assignment_Id': '14295M',
    'Assignment_Title': 'Midterm',
    'Weight': 0.2,
    'Grades': [{'Student_ID': 'jrp86y', 'Score': 86},
     {'Student_ID': 'mcf5yc', 'Score': 97},
     {'Student_ID': 'rin7tx', 'Score': 95},
     {'Student_ID': 'vip4my', 'Score': 89},
     {'Student_ID': 'eru9fh', 'Score': 98}]},
   {'Assignment_Id': '14295F',
    'Assignment_Title': 'Final',
    'Weight': 0.6,
    'Grades': [{'Student_ID': 'jrp86y', 'Score': 66},
     {'Student_ID': 'mcf5yc', 'Score': 87},
     {'Student_ID': 'rin7tx', 'Score': 73},
     {'Student_ID': 'vip4my', 'Score': 96},
     {'Student_ID': 'eru9fh', 'Score': 63}]}]},
 {'Code': 14730,
  'Course_Name': 'COMM_3410',
  'Students': [{'Student_ID': 'rqb6bc',
    'First_Name': 'Melissa',
    'Last_Name': 'Zheng',
    'Email': 'rqb6bc@virginia.edu'},
   {'Student_ID': 'zds3st',
    'First_Name': 'Isaac',
    'Last_Name': 'Tabor',
    'Email': 'zds3st@virginia.edu'},
   {'Student_ID': 'pfg9yq',
    'First_Name': 'Anya',
    'Last_Name': 'Hariharan',
    'Email': 'pfg9yq@virginia.edu'},
   {'Student_ID': 'jrp86y',
    'First_Name': 'Peter',
    'Last_Name': 'Park',
    'Email': 'jrp86y@virginia.edu'},
   {'Student_ID': 'rin7tx',
    'First_Name': 'Cheryl',
    'Last_Name': 'Abernathy',
    'Email': 'rin7tx@virginia.edu'}],
  'Assignments': [{'Assignment_Id': '14730E1',
    'Assignment_Title': 'Exam 1',
    'Weight': 0.1,
    'Grades': [{'Student_ID': 'rqb6bc', 'Score': 86},
     {'Student_ID': 'zds3st', 'Score': 67},
     {'Student_ID': 'pfg9yq', 'Score': 56},
     {'Student_ID': 'jrp86y', 'Score': 97},
     {'Student_ID': 'rin7tx', 'Score': 72}]},
   {'Assignment_Id': '14730E2',
    'Assignment_Title': 'Exam 2',
    'Weight': 0.1,
    'Grades': [{'Student_ID': 'rqb6bc', 'Score': 94},
     {'Student_ID': 'zds3st', 'Score': 70},
     {'Student_ID': 'pfg9yq', 'Score': 62},
     {'Student_ID': 'jrp86y', 'Score': 78},
     {'Student_ID': 'rin7tx', 'Score': 80}]},
   {'Assignment_Id': '14730M',
    'Assignment_Title': 'Midterm',
    'Weight': 0.2,
    'Grades': [{'Student_ID': 'rqb6bc', 'Score': 82},
     {'Student_ID': 'zds3st', 'Score': 77},
     {'Student_ID': 'pfg9yq', 'Score': 91},
     {'Student_ID': 'jrp86y', 'Score': 65},
     {'Student_ID': 'rin7tx', 'Score': 66}]},
   {'Assignment_Id': '14730F',
    'Assignment_Title': 'Final',
    'Weight': 0.6,
    'Grades': [{'Student_ID': 'rqb6bc', 'Score': 76},
     {'Student_ID': 'zds3st', 'Score': 53},
     {'Student_ID': 'pfg9yq', 'Score': 84},
     {'Student_ID': 'jrp86y', 'Score': 58},
     {'Student_ID': 'rin7tx', 'Score': 87}]}]},
 {'Code': 14731,
  'Course_Name': 'COMM_3410',
  'Students': [{'Student_ID': 'fmp6yj',
    'First_Name': 'Laura',
    'Last_Name': 'Peters',
    'Email': 'fmp6yj@virginia.edu'},
   {'Student_ID': 'vip4my',
    'First_Name': 'Colleen',
    'Last_Name': 'Lindstrom',
    'Email': 'vip4my@virginia.edu'},
   {'Student_ID': 'eru9fh',
    'First_Name': 'Robin',
    'Last_Name': 'Park',
    'Email': 'eru9fh@virginia.edu'},
   {'Student_ID': 'fpn8kb',
    'First_Name': 'Nicholas',
    'Last_Name': 'Spielberg',
    'Email': 'fpn8kb@virginia.edu'},
   {'Student_ID': 'imc4bv',
    'First_Name': 'Douglas',
    'Last_Name': 'Polansky',
    'Email': 'imc4bv@virginia.edu'}],
  'Assignments': [{'Assignment_Id': '14731E1',
    'Assignment_Title': 'Exam 1',
    'Weight': 0.1,
    'Grades': [{'Student_ID': 'fmp6yj', 'Score': 87},
     {'Student_ID': 'vip4my', 'Score': 65},
     {'Student_ID': 'eru9fh', 'Score': 45},
     {'Student_ID': 'fpn8kb', 'Score': 100},
     {'Student_ID': 'imc4bv', 'Score': 79}]},
   {'Assignment_Id': '14731E2',
    'Assignment_Title': 'Exam 2',
    'Weight': 0.1,
    'Grades': [{'Student_ID': 'fmp6yj', 'Score': 77},
     {'Student_ID': 'vip4my', 'Score': 80},
     {'Student_ID': 'eru9fh', 'Score': 65},
     {'Student_ID': 'fpn8kb', 'Score': 99},
     {'Student_ID': 'imc4bv', 'Score': 92}]},
   {'Assignment_Id': '14731M',
    'Assignment_Title': 'Midterm',
    'Weight': 0.2,
    'Grades': [{'Student_ID': 'fmp6yj', 'Score': 78},
     {'Student_ID': 'vip4my', 'Score': 98},
     {'Student_ID': 'eru9fh', 'Score': 43},
     {'Student_ID': 'fpn8kb', 'Score': 83},
     {'Student_ID': 'imc4bv', 'Score': 87}]},
   {'Assignment_Id': '14731F',
    'Assignment_Title': 'Final',
    'Weight': 0.6,
    'Grades': [{'Student_ID': 'fmp6yj', 'Score': 76},
     {'Student_ID': 'vip4my', 'Score': 56},
     {'Student_ID': 'eru9fh', 'Score': 98},
     {'Student_ID': 'fpn8kb', 'Score': 84},
     {'Student_ID': 'imc4bv', 'Score': 99}]}]},
 {'Code': 15413,
  'Course_Name': 'APMA_3110',
  'Students': [{'Student_ID': 'svw7gw',
    'First_Name': 'Edward',
    'Last_Name': 'Lee',
    'Email': 'svw7gw@virginia.edu'},
   {'Student_ID': 'clw3dh',
    'First_Name': 'Felipe',
    'Last_Name': 'Mendez',
    'Email': 'clw3dh@virginia.edu'},
   {'Student_ID': 'vip4my',
    'First_Name': 'Colleen',
    'Last_Name': 'Lindstrom',
    'Email': 'vip4my@virginia.edu'},
   {'Student_ID': 'tmz7bd',
    'First_Name': 'Brittney',
    'Last_Name': 'Reed',
    'Email': 'tmz7bd@virginia.edu'},
   {'Student_ID': 'wdk0je',
    'First_Name': 'Tyrone',
    'Last_Name': 'Twain',
    'Email': 'wdk0je@virginia.edu'}],
  'Assignments': [{'Assignment_Id': '15413E1',
    'Assignment_Title': 'Exam 1',
    'Weight': 0.1,
    'Grades': [{'Student_ID': 'svw7gw', 'Score': 88},
     {'Student_ID': 'clw3dh', 'Score': 94},
     {'Student_ID': 'vip4my', 'Score': 78},
     {'Student_ID': 'tmz7bd', 'Score': 75},
     {'Student_ID': 'wdk0je', 'Score': 85}]},
   {'Assignment_Id': '15413E2',
    'Assignment_Title': 'Exam 2',
    'Weight': 0.1,
    'Grades': [{'Student_ID': 'svw7gw', 'Score': 98},
     {'Student_ID': 'clw3dh', 'Score': 82},
     {'Student_ID': 'vip4my', 'Score': 97},
     {'Student_ID': 'tmz7bd', 'Score': 89},
     {'Student_ID': 'wdk0je', 'Score': 95}]},
   {'Assignment_Id': '15413M',
    'Assignment_Title': 'Midterm',
    'Weight': 0.2,
    'Grades': [{'Student_ID': 'svw7gw', 'Score': 63},
     {'Student_ID': 'clw3dh', 'Score': 76},
     {'Student_ID': 'vip4my', 'Score': 87},
     {'Student_ID': 'tmz7bd', 'Score': 96},
     {'Student_ID': 'wdk0je', 'Score': 73}]},
   {'Assignment_Id': '15413F',
    'Assignment_Title': 'Final',
    'Weight': 0.6,
    'Grades': [{'Student_ID': 'svw7gw', 'Score': 60},
     {'Student_ID': 'clw3dh', 'Score': 56},
     {'Student_ID': 'vip4my', 'Score': 81},
     {'Student_ID': 'tmz7bd', 'Score': 68},
     {'Student_ID': 'wdk0je', 'Score': 86}]}]},
 {'Code': 15762,
  'Course_Name': 'MATH_3350',
  'Students': [{'Student_ID': 'rqb6bc',
    'First_Name': 'Melissa',
    'Last_Name': 'Zheng',
    'Email': 'rqb6bc@virginia.edu'},
   {'Student_ID': 'ppz2ry',
    'First_Name': 'Alex',
    'Last_Name': 'Jones',
    'Email': 'ppz2ry@virginia.edu'},
   {'Student_ID': 'pfg9yq',
    'First_Name': 'Anya',
    'Last_Name': 'Hariharan',
    'Email': 'pfg9yq@virginia.edu'},
   {'Student_ID': 'jrp86y',
    'First_Name': 'Peter',
    'Last_Name': 'Park',
    'Email': 'jrp86y@virginia.edu'},
   {'Student_ID': 'mcf5yc',
    'First_Name': 'Aryan',
    'Last_Name': 'Prabhudesai',
    'Email': 'mcf5yc@virginia.edu'}],
  'Assignments': [{'Assignment_Id': '15762E1',
    'Assignment_Title': 'Exam 1',
    'Weight': 0.1,
    'Grades': [{'Student_ID': 'rqb6bc', 'Score': 79},
     {'Student_ID': 'pfg9yq', 'Score': 80},
     {'Student_ID': 'jrp86y', 'Score': 85},
     {'Student_ID': 'mcf5yc', 'Score': 68}]},
   {'Assignment_Id': '15762E2',
    'Assignment_Title': 'Exam 2',
    'Weight': 0.1,
    'Grades': [{'Student_ID': 'rqb6bc', 'Score': 92},
     {'Student_ID': 'pfg9yq', 'Score': 92},
     {'Student_ID': 'jrp86y', 'Score': 77},
     {'Student_ID': 'mcf5yc', 'Score': 62}]},
   {'Assignment_Id': '15762M',
    'Assignment_Title': 'Midterm',
    'Weight': 0.2,
    'Grades': [{'Student_ID': 'rqb6bc', 'Score': 87},
     {'Student_ID': 'pfg9yq', 'Score': 93},
     {'Student_ID': 'jrp86y', 'Score': 90},
     {'Student_ID': 'mcf5yc', 'Score': 59}]},
   {'Assignment_Id': '15762F',
    'Assignment_Title': 'Final',
    'Weight': 0.6,
    'Grades': [{'Student_ID': 'rqb6bc', 'Score': 99},
     {'Student_ID': 'pfg9yq', 'Score': 91},
     {'Student_ID': 'jrp86y', 'Score': 95},
     {'Student_ID': 'mcf5yc', 'Score': 72}]}]},
 {'Code': 15763,
  'Course_Name': 'MATH_3350',
  'Students': [{'Student_ID': 'fmp6yj',
    'First_Name': 'Laura',
    'Last_Name': 'Peters',
    'Email': 'fmp6yj@virginia.edu'},
   {'Student_ID': 'rin7tx',
    'First_Name': 'Cheryl',
    'Last_Name': 'Abernathy',
    'Email': 'rin7tx@virginia.edu'},
   {'Student_ID': 'vip4my',
    'First_Name': 'Colleen',
    'Last_Name': 'Lindstrom',
    'Email': 'vip4my@virginia.edu'},
   {'Student_ID': 'eru9fh',
    'First_Name': 'Robin',
    'Last_Name': 'Park',
    'Email': 'eru9fh@virginia.edu'},
   {'Student_ID': 'fpn8kb',
    'First_Name': 'Nicholas',
    'Last_Name': 'Spielberg',
    'Email': 'fpn8kb@virginia.edu'}],
  'Assignments': [{'Assignment_Id': '15763E1',
    'Assignment_Title': 'Exam 1',
    'Weight': 0.1,
    'Grades': [{'Student_ID': 'fmp6yj', 'Score': 80},
     {'Student_ID': 'rin7tx', 'Score': 88},
     {'Student_ID': 'vip4my', 'Score': 90},
     {'Student_ID': 'eru9fh', 'Score': 88},
     {'Student_ID': 'fpn8kb', 'Score': 90}]},
   {'Assignment_Id': '15763E2',
    'Assignment_Title': 'Exam 2',
    'Weight': 0.1,
    'Grades': [{'Student_ID': 'fmp6yj', 'Score': 85},
     {'Student_ID': 'rin7tx', 'Score': 90},
     {'Student_ID': 'vip4my', 'Score': 72},
     {'Student_ID': 'eru9fh', 'Score': 90},
     {'Student_ID': 'fpn8kb', 'Score': 95}]},
   {'Assignment_Id': '15763F',
    'Assignment_Title': 'Midterm',
    'Weight': 0.2,
    'Grades': [{'Student_ID': 'fmp6yj', 'Score': 95},
     {'Student_ID': 'rin7tx', 'Score': 95},
     {'Student_ID': 'vip4my', 'Score': 100},
     {'Student_ID': 'eru9fh', 'Score': 72},
     {'Student_ID': 'fpn8kb', 'Score': 86}]},
   {'Assignment_Id': '15763M',
    'Assignment_Title': 'Final',
    'Weight': 0.6,
    'Grades': [{'Student_ID': 'fmp6yj', 'Score': 90},
     {'Student_ID': 'rin7tx', 'Score': 77},
     {'Student_ID': 'vip4my', 'Score': 88},
     {'Student_ID': 'eru9fh', 'Score': 95},
     {'Student_ID': 'fpn8kb', 'Score': 100}]}]},
 {'Code': 15764,
  'Course_Name': 'MATH_3350',
  'Students': [{'Student_ID': 'svw7gw',
    'First_Name': 'Edward',
    'Last_Name': 'Lee',
    'Email': 'svw7gw@virginia.edu'},
   {'Student_ID': 'clw3dh',
    'First_Name': 'Felipe',
    'Last_Name': 'Mendez',
    'Email': 'clw3dh@virginia.edu'},
   {'Student_ID': 'imc4bv',
    'First_Name': 'Douglas',
    'Last_Name': 'Polansky',
    'Email': 'imc4bv@virginia.edu'},
   {'Student_ID': 'tmz7bd',
    'First_Name': 'Brittney',
    'Last_Name': 'Reed',
    'Email': 'tmz7bd@virginia.edu'},
   {'Student_ID': 'wdk0je',
    'First_Name': 'Tyrone',
    'Last_Name': 'Twain',
    'Email': 'wdk0je@virginia.edu'}],
  'Assignments': [{'Assignment_Id': '15764E1',
    'Assignment_Title': 'Exam 1',
    'Weight': 0.1,
    'Grades': [{'Student_ID': 'svw7gw', 'Score': 90},
     {'Student_ID': 'clw3dh', 'Score': 93},
     {'Student_ID': 'imc4bv', 'Score': 90},
     {'Student_ID': 'tmz7bd', 'Score': 90},
     {'Student_ID': 'wdk0je', 'Score': 93}]},
   {'Assignment_Id': '15764E2',
    'Assignment_Title': 'Exam 2',
    'Weight': 0.1,

In [17]:
print(student_courses_merged[student_courses_merged['Code'] == 11386])

     Code Student_ID First_Name  Last_Name                Email
2   11386     rqb6bc    Melissa      Zheng  rqb6bc@virginia.edu
11  11386     zds3st      Isaac      Tabor  zds3st@virginia.edu
21  11386     ppz2ry       Alex      Jones  ppz2ry@virginia.edu
25  11386     pfg9yq       Anya  Hariharan  pfg9yq@virginia.edu
30  11386     jrp86y      Peter       Park  jrp86y@virginia.edu

In [18]:
# Connect to MongoDB
client = MongoClient('mongodb://localhost:27017/')
db = client['mydatabase']
courses_collection = db['courses']

# Insert the nested data
courses_collection.insert_many(nested_data)

InsertManyResult([ObjectId('6658c29812cb5103b79ca931'), ObjectId('6658c29812cb5103b79ca932'), ObjectId('6658c29812cb5103b79ca933'), ObjectId('6658c29812cb5103b79ca934'), ObjectId('6658c29812cb5103b79ca935'), ObjectId('6658c29812cb5103b79ca936'), ObjectId('6658c29812cb5103b79ca937'), ObjectId('6658c29812cb5103b79ca938'), ObjectId('6658c29812cb5103b79ca939'), ObjectId('6658c29812cb5103b79ca93a'), ObjectId('6658c29812cb5103b79ca93b'), ObjectId('6658c29812cb5103b79ca93c')], acknowledged=True)

## QUERY

In [19]:
# Connect to MongoDB
client = MongoClient('mongodb://localhost:27017/')
db = client['mydatabase']

In [20]:
# Aggregation pipeline
pipeline = [
    # Match documents with the course code 12736
    {"$match": {"Code": 12736}},
    
    # Unwind the Students array
    {"$unwind": "$Students"},
    
    # Project to include the required fields
    {"$project": {
        "_id": 0,
        "Course_Name": 1,
        "Student_First_Name": "$Students.First_Name",
        "Student_Last_Name": "$Students.Last_Name"
    }}
]

# Perform aggregation
result = db.courses.aggregate(pipeline)

# Print the results
for doc in result:
    print(doc)

{'Course_Name': 'COMM_2020', 'Student_First_Name': 'Melissa', 'Student_Last_Name': 'Zheng'}
{'Course_Name': 'COMM_2020', 'Student_First_Name': 'Edward', 'Student_Last_Name': 'Lee'}
{'Course_Name': 'COMM_2020', 'Student_First_Name': 'Isaac', 'Student_Last_Name': 'Tabor'}
{'Course_Name': 'COMM_2020', 'Student_First_Name': 'Laura', 'Student_Last_Name': 'Peters'}
{'Course_Name': 'COMM_2020', 'Student_First_Name': 'Felipe', 'Student_Last_Name': 'Mendez'}

In [25]:
pipeline = [
    # Unwind the Students array
    {"$unwind": "$Students"},
    
    # Unwind the Assignments array
    {"$unwind": "$Assignments"},
    
    # Unwind the Grades array
    {"$unwind": "$Assignments.Grades"},
    
    # Group by necessary fields to calculate the total score and total weight for each student in each course
    {"$group": {
        "_id": {
            "Student_ID": "$Students.Student_ID",
            "Course_Code": "$Code",
            "Course_Name": "$Course_Name",
            "First_Name": "$Students.First_Name",
            "Last_Name": "$Students.Last_Name"
        },
        "Total_Score": {
            "$sum": {
                "$multiply": ["$Assignments.Grades.Score", "$Assignments.Weight"]
            }
        },
        "Total_Weight": {
            "$sum": "$Assignments.Weight"
        }
    }},
    
    # Project intermediate results to debug
    {"$project": {
        "_id": 0,
        "Student_ID": "$_id.Student_ID",
        "Course_Code": "$_id.Course_Code",
        "First_Name": "$_id.First_Name",
        "Last_Name": "$_id.Last_Name",
        "Course_Name": "$_id.Course_Name",
        "CourseGrade": {
            "$cond": {
                "if": {"$eq": ["$Total_Weight", 0]},
                "then": None,  # or you could use 0 or another default value
                "else": {"$divide": ["$Total_Score", "$Total_Weight"]}
            }
        }
    }}
]
# Perform aggregation
result = db.courses.aggregate(pipeline)
# Print the results
for doc in result:
    print(doc)

{'Student_ID': 'imc4bv', 'Course_Code': 21031, 'First_Name': 'Douglas', 'Last_Name': 'Polansky', 'Course_Name': 'STAT_1601', 'CourseGrade': 78.12}
{'Student_ID': 'ppz2ry', 'Course_Code': 11386, 'First_Name': 'Alex', 'Last_Name': 'Jones', 'Course_Name': 'SLAV_2360', 'CourseGrade': 80.325}
{'Student_ID': 'jrp86y', 'Course_Code': 12564, 'First_Name': 'Peter', 'Last_Name': 'Park', 'Course_Name': 'STAT_1601', 'CourseGrade': 70.675}
{'Student_ID': 'svw7gw', 'Course_Code': 12736, 'First_Name': 'Edward', 'Last_Name': 'Lee', 'Course_Name': 'COMM_2020', 'CourseGrade': 67.14}
{'Student_ID': 'fpn8kb', 'Course_Code': 12645, 'First_Name': 'Nicholas', 'Last_Name': 'Spielberg', 'Course_Name': 'STAT_1601', 'CourseGrade': 62.02}
{'Student_ID': 'mcf5yc', 'Course_Code': 15762, 'First_Name': 'Aryan', 'Last_Name': 'Prabhudesai', 'Course_Name': 'MATH_3350', 'CourseGrade': 85.875}
{'Student_ID': 'wdk0je', 'Course_Code': 15413, 'First_Name': 'Tyrone', 'Last_Name': 'Twain', 'Course_Name': 'APMA_3110', 'CourseGrade': 75.54}
{'Student_ID': 'mcf5yc', 'Course_Code': 12564, 'First_Name': 'Aryan', 'Last_Name': 'Prabhudesai', 'Course_Name': 'STAT_1601', 'CourseGrade': 70.675}
{'Student_ID': 'pfg9yq', 'Course_Code': 15762, 'First_Name': 'Anya', 'Last_Name': 'Hariharan', 'Course_Name': 'MATH_3350', 'CourseGrade': 85.875}
{'Student_ID': 'eru9fh', 'Course_Code': 14731, 'First_Name': 'Robin', 'Last_Name': 'Park', 'Course_Name': 'COMM_3410', 'CourseGrade': 80.9}
{'Student_ID': 'vip4my', 'Course_Code': 12645, 'First_Name': 'Colleen', 'Last_Name': 'Lindstrom', 'Course_Name': 'STAT_1601', 'CourseGrade': 62.02}
{'Student_ID': 'ppz2ry', 'Course_Code': 12564, 'First_Name': 'Alex', 'Last_Name': 'Jones', 'Course_Name': 'STAT_1601', 'CourseGrade': 70.675}
{'Student_ID': 'vip4my', 'Course_Code': 15413, 'First_Name': 'Colleen', 'Last_Name': 'Lindstrom', 'Course_Name': 'APMA_3110', 'CourseGrade': 75.54}
{'Student_ID': 'zds3st', 'Course_Code': 11386, 'First_Name': 'Isaac', 'Last_Name': 'Tabor', 'Course_Name': 'SLAV_2360', 'CourseGrade': 80.325}
{'Student_ID': 'ppz2ry', 'Course_Code': 15762, 'First_Name': 'Alex', 'Last_Name': 'Jones', 'Course_Name': 'MATH_3350', 'CourseGrade': 85.875}
{'Student_ID': 'svw7gw', 'Course_Code': 15413, 'First_Name': 'Edward', 'Last_Name': 'Lee', 'Course_Name': 'APMA_3110', 'CourseGrade': 75.54}
{'Student_ID': 'fmp6yj', 'Course_Code': 15763, 'First_Name': 'Laura', 'Last_Name': 'Peters', 'Course_Name': 'MATH_3350', 'CourseGrade': 89.28}
{'Student_ID': 'fmp6yj', 'Course_Code': 14731, 'First_Name': 'Laura', 'Last_Name': 'Peters', 'Course_Name': 'COMM_3410', 'CourseGrade': 80.9}
{'Student_ID': 'vip4my', 'Course_Code': 14731, 'First_Name': 'Colleen', 'Last_Name': 'Lindstrom', 'Course_Name': 'COMM_3410', 'CourseGrade': 80.9}
{'Student_ID': 'rin7tx', 'Course_Code': 15763, 'First_Name': 'Cheryl', 'Last_Name': 'Abernathy', 'Course_Name': 'MATH_3350', 'CourseGrade': 89.28}
{'Student_ID': 'rin7tx', 'Course_Code': 14730, 'First_Name': 'Cheryl', 'Last_Name': 'Abernathy', 'Course_Name': 'COMM_3410', 'CourseGrade': 73.44}
{'Student_ID': 'tmz7bd', 'Course_Code': 15413, 'First_Name': 'Brittney', 'Last_Name': 'Reed', 'Course_Name': 'APMA_3110', 'CourseGrade': 75.54}
{'Student_ID': 'fmp6yj', 'Course_Code': 12736, 'First_Name': 'Laura', 'Last_Name': 'Peters', 'Course_Name': 'COMM_2020', 'CourseGrade': 67.14}
{'Student_ID': 'imc4bv', 'Course_Code': 14731, 'First_Name': 'Douglas', 'Last_Name': 'Polansky', 'Course_Name': 'COMM_3410', 'CourseGrade': 80.9}
{'Student_ID': 'zds3st', 'Course_Code': 12736, 'First_Name': 'Isaac', 'Last_Name': 'Tabor', 'Course_Name': 'COMM_2020', 'CourseGrade': 67.14}
{'Student_ID': 'vip4my', 'Course_Code': 15763, 'First_Name': 'Colleen', 'Last_Name': 'Lindstrom', 'Course_Name': 'MATH_3350', 'CourseGrade': 89.28}
{'Student_ID': 'pfg9yq', 'Course_Code': 12564, 'First_Name': 'Anya', 'Last_Name': 'Hariharan', 'Course_Name': 'STAT_1601', 'CourseGrade': 70.675}
{'Student_ID': 'svw7gw', 'Course_Code': 15764, 'First_Name': 'Edward', 'Last_Name': 'Lee', 'Course_Name': 'MATH_3350', 'CourseGrade': 90.14}
{'Student_ID': 'fpn8kb', 'Course_Code': 14731, 'First_Name': 'Nicholas', 'Last_Name': 'Spielberg', 'Course_Name': 'COMM_3410', 'CourseGrade': 80.9}
{'Student_ID': 'jrp86y', 'Course_Code': 14295, 'First_Name': 'Peter', 'Last_Name': 'Park', 'Course_Name': 'COMM_2020', 'CourseGrade': 80.47999999999999}
{'Student_ID': 'zds3st', 'Course_Code': 12564, 'First_Name': 'Isaac', 'Last_Name': 'Tabor', 'Course_Name': 'STAT_1601', 'CourseGrade': 70.675}
{'Student_ID': 'rin7tx', 'Course_Code': 14295, 'First_Name': 'Cheryl', 'Last_Name': 'Abernathy', 'Course_Name': 'COMM_2020', 'CourseGrade': 80.47999999999999}
{'Student_ID': 'rqb6bc', 'Course_Code': 15762, 'First_Name': 'Melissa', 'Last_Name': 'Zheng', 'Course_Name': 'MATH_3350', 'CourseGrade': 85.875}
{'Student_ID': 'pfg9yq', 'Course_Code': 14730, 'First_Name': 'Anya', 'Last_Name': 'Hariharan', 'Course_Name': 'COMM_3410', 'CourseGrade': 73.44}
{'Student_ID': 'jrp86y', 'Course_Code': 14730, 'First_Name': 'Peter', 'Last_Name': 'Park', 'Course_Name': 'COMM_3410', 'CourseGrade': 73.44}
{'Student_ID': 'pfg9yq', 'Course_Code': 11386, 'First_Name': 'Anya', 'Last_Name': 'Hariharan', 'Course_Name': 'SLAV_2360', 'CourseGrade': 80.325}
{'Student_ID': 'eru9fh', 'Course_Code': 15763, 'First_Name': 'Robin', 'Last_Name': 'Park', 'Course_Name': 'MATH_3350', 'CourseGrade': 89.28}
{'Student_ID': 'fmp6yj', 'Course_Code': 12645, 'First_Name': 'Laura', 'Last_Name': 'Peters', 'Course_Name': 'STAT_1601', 'CourseGrade': 62.02}
{'Student_ID': 'rqb6bc', 'Course_Code': 12736, 'First_Name': 'Melissa', 'Last_Name': 'Zheng', 'Course_Name': 'COMM_2020', 'CourseGrade': 67.14}
{'Student_ID': 'jrp86y', 'Course_Code': 15762, 'First_Name': 'Peter', 'Last_Name': 'Park', 'Course_Name': 'MATH_3350', 'CourseGrade': 85.875}
{'Student_ID': 'tmz7bd', 'Course_Code': 21031, 'First_Name': 'Brittney', 'Last_Name': 'Reed', 'Course_Name': 'STAT_1601', 'CourseGrade': 78.12}
{'Student_ID': 'wdk0je', 'Course_Code': 21031, 'First_Name': 'Tyrone', 'Last_Name': 'Twain', 'Course_Name': 'STAT_1601', 'CourseGrade': 78.12}
{'Student_ID': 'rqb6bc', 'Course_Code': 14730, 'First_Name': 'Melissa', 'Last_Name': 'Zheng', 'Course_Name': 'COMM_3410', 'CourseGrade': 73.44}
{'Student_ID': 'rin7tx', 'Course_Code': 12645, 'First_Name': 'Cheryl', 'Last_Name': 'Abernathy', 'Course_Name': 'STAT_1601', 'CourseGrade': 62.02}
{'Student_ID': 'clw3dh', 'Course_Code': 15413, 'First_Name': 'Felipe', 'Last_Name': 'Mendez', 'Course_Name': 'APMA_3110', 'CourseGrade': 75.54}
{'Student_ID': 'imc4bv', 'Course_Code': 15764, 'First_Name': 'Douglas', 'Last_Name': 'Polansky', 'Course_Name': 'MATH_3350', 'CourseGrade': 90.14}
{'Student_ID': 'svw7gw', 'Course_Code': 21031, 'First_Name': 'Edward', 'Last_Name': 'Lee', 'Course_Name': 'STAT_1601', 'CourseGrade': 78.12}
{'Student_ID': 'jrp86y', 'Course_Code': 11386, 'First_Name': 'Peter', 'Last_Name': 'Park', 'Course_Name': 'SLAV_2360', 'CourseGrade': 80.325}
{'Student_ID': 'rqb6bc', 'Course_Code': 11386, 'First_Name': 'Melissa', 'Last_Name': 'Zheng', 'Course_Name': 'SLAV_2360', 'CourseGrade': 80.325}
{'Student_ID': 'tmz7bd', 'Course_Code': 15764, 'First_Name': 'Brittney', 'Last_Name': 'Reed', 'Course_Name': 'MATH_3350', 'CourseGrade': 90.14}
{'Student_ID': 'eru9fh', 'Course_Code': 14295, 'First_Name': 'Robin', 'Last_Name': 'Park', 'Course_Name': 'COMM_2020', 'CourseGrade': 80.47999999999999}
{'Student_ID': 'vip4my', 'Course_Code': 14295, 'First_Name': 'Colleen', 'Last_Name': 'Lindstrom', 'Course_Name': 'COMM_2020', 'CourseGrade': 80.47999999999999}
{'Student_ID': 'eru9fh', 'Course_Code': 12645, 'First_Name': 'Robin', 'Last_Name': 'Park', 'Course_Name': 'STAT_1601', 'CourseGrade': 62.02}
{'Student_ID': 'mcf5yc', 'Course_Code': 14295, 'First_Name': 'Aryan', 'Last_Name': 'Prabhudesai', 'Course_Name': 'COMM_2020', 'CourseGrade': 80.47999999999999}
{'Student_ID': 'zds3st', 'Course_Code': 14730, 'First_Name': 'Isaac', 'Last_Name': 'Tabor', 'Course_Name': 'COMM_3410', 'CourseGrade': 73.44}
{'Student_ID': 'fpn8kb', 'Course_Code': 15763, 'First_Name': 'Nicholas', 'Last_Name': 'Spielberg', 'Course_Name': 'MATH_3350', 'CourseGrade': 89.28}
{'Student_ID': 'clw3dh', 'Course_Code': 12736, 'First_Name': 'Felipe', 'Last_Name': 'Mendez', 'Course_Name': 'COMM_2020', 'CourseGrade': 67.14}
{'Student_ID': 'clw3dh', 'Course_Code': 15764, 'First_Name': 'Felipe', 'Last_Name': 'Mendez', 'Course_Name': 'MATH_3350', 'CourseGrade': 90.14}
{'Student_ID': 'wdk0je', 'Course_Code': 15764, 'First_Name': 'Tyrone', 'Last_Name': 'Twain', 'Course_Name': 'MATH_3350', 'CourseGrade': 90.14}
{'Student_ID': 'clw3dh', 'Course_Code': 21031, 'First_Name': 'Felipe', 'Last_Name': 'Mendez', 'Course_Name': 'STAT_1601', 'CourseGrade': 78.12}

In [26]:
pipeline = [
    # Match the specific Student_ID
    {"$match": {"Students.Student_ID": "zds3st"}},
    
    # Unwind the Students array
    {"$unwind": "$Students"},
    
    # Further filter for the specific Student_ID after unwinding
    {"$match": {"Students.Student_ID": "zds3st"}},

    # Lookup to join Assignments and unwind Grades
    {
        "$lookup": {
            "from": "courses",
            "let": {"courseCode": "$Code"},
            "pipeline": [
                {"$match": {"$expr": {"$eq": ["$Code", "$$courseCode"]}}},
                {"$unwind": "$Assignments"},
                {"$unwind": "$Assignments.Grades"},
                {
                    "$project": {
                        "_id": 0,
                        "Assignment_Weight": "$Assignments.Weight",
                        "Grade_Score": "$Assignments.Grades.Score"
                    }
                }
            ],
            "as": "AssignmentsWithGrades"
        }
    },
    
    # Unwind the joined array
    {"$unwind": "$AssignmentsWithGrades"},
    
    # Group by necessary fields to calculate the total score and total weight for each student in each course
    {
        "$group": {
            "_id": {
                "Student_ID": "$Students.Student_ID",
                "Course_Code": "$Code",
                "Course_Name": "$Course_Name",
                "First_Name": "$Students.First_Name",
                "Last_Name": "$Students.Last_Name"
            },
            "Total_Score": {
                "$sum": {
                    "$multiply": [
                        "$AssignmentsWithGrades.Grade_Score",
                        "$AssignmentsWithGrades.Assignment_Weight"
                    ]
                }
            },
            "Total_Weight": {"$sum": "$AssignmentsWithGrades.Assignment_Weight"}
        }
    },
    
    # Project the final results
    {
        "$project": {
            "_id": 0,
            "Student_ID": "$_id.Student_ID",
            "Course_Code": "$_id.Course_Code",
            "First_Name": "$_id.First_Name",
            "Last_Name": "$_id.Last_Name",
            "Course_Name": "$_id.Course_Name",
            "CourseGrade": {
                "$cond": {
                    "if": {"$eq": ["$Total_Weight", 0]},
                    "then": None,  # or you could use 0 or another default value
                    "else": {"$divide": ["$Total_Score", "$Total_Weight"]}
                }
            }
        }
    }
]

# Perform aggregation
result = db.courses.aggregate(pipeline)

# Print the results
for doc in result:
    print(doc)

{'Student_ID': 'zds3st', 'Course_Code': 12736, 'First_Name': 'Isaac', 'Last_Name': 'Tabor', 'Course_Name': 'COMM_2020', 'CourseGrade': 67.14}
{'Student_ID': 'zds3st', 'Course_Code': 14730, 'First_Name': 'Isaac', 'Last_Name': 'Tabor', 'Course_Name': 'COMM_3410', 'CourseGrade': 73.44}
{'Student_ID': 'zds3st', 'Course_Code': 12564, 'First_Name': 'Isaac', 'Last_Name': 'Tabor', 'Course_Name': 'STAT_1601', 'CourseGrade': 70.675}
{'Student_ID': 'zds3st', 'Course_Code': 11386, 'First_Name': 'Isaac', 'Last_Name': 'Tabor', 'Course_Name': 'SLAV_2360', 'CourseGrade': 80.325}